import type { CatalogAllergenId } from '$lib/domain/models';

export type CategoryStrings = {
  name: string; // full Czech category name shown in grids and lists
};

export const categoryStrings = {
  dairy: { name: 'Mléčné výrobky' },
  eggs: { name: 'Vejce' },
  wheat: { name: 'Pšenice / lepek' },
  oats: { name: 'Oves' },
  soy: { name: 'Sója' },
  nuts: { name: 'Ořechy' },
  peanuts: { name: 'Arašídy' },
  fish: { name: 'Ryby' },
  shellfish: { name: 'Korýši a měkkýši' },
  citrus: { name: 'Citrusy' },
  cocoa: { name: 'Čokoláda / kakao' },
  tomatoes: { name: 'Rajčata' },
  strawberries: { name: 'Jahody' },
  raspberries: { name: 'Maliny' },
  sesame: { name: 'Sezamové výrobky' },
  chicken: { name: 'Kuřecí maso' },
  honey: { name: 'Med' },
  // ADR-0017 slice 6 — regional expansion
  grains: { name: 'Obiloviny (kromě pšenice)' },
  seeds: { name: 'Semínka' },
  legumes: { name: 'Luštěniny' },
  fruit: { name: 'Ovoce' },
  'exotic-fruit': { name: 'Exotické ovoce' },
  'carrot-root-veg': { name: 'Kořenová zelenina' },
  'cabbage-brassica': { name: 'Zelí a košťálová zelenina' },
  'onion-garlic': { name: 'Cibule a česnek' },
  potato: { name: 'Brambory' },
  mushroom: { name: 'Houby' },
  celery: { name: 'Celer' },
  'other-vegetables': { name: 'Ostatní zelenina' },
  meat: { name: 'Maso' },
  beef: { name: 'Hovězí bílkovina' },
  mustard: { name: 'Hořčice' },
  'sulphites-additives': { name: 'Siřičitany a aditiva' },
  'vinegar-fermented': { name: 'Ocet a kvašené potraviny' },
  yeast: { name: 'Kvasnice / droždí' },
  sweeteners: { name: 'Sladidla' },
  'spices-herbs': { name: 'Koření a bylinky' },
  'coffee-tea': { name: 'Káva a čaj' },
} as const satisfies Record<CatalogAllergenId, CategoryStrings>;

export const subitemStrings = {
  'dairy:milk': 'Kravské mléko',
  'dairy:butter': 'Máslo',
  'dairy:cheese': 'Sýr',
  'dairy:yogurt': 'Jogurt',
  'dairy:cream': 'Smetana',
  'dairy:cottage': 'Tvaroh',
  'eggs:egg-white': 'Bílek',
  'eggs:egg-yolk': 'Žloutek',
  'wheat:bread': 'Chléb / rohlík',
  'wheat:pasta': 'Těstoviny',
  'wheat:flour': 'Mouka',
  'wheat:gluten': 'Lepek (gluten)',
  'soy:soy-milk': 'Sójové mléko',
  'soy:tofu': 'Tofu',
  'soy:soy-sauce': 'Sójová omáčka',
  'soy:soy-lecithin': 'Sójový lecitin',
  'nuts:peanuts': 'Arašídy',
  'nuts:walnuts': 'Vlašské ořechy',
  'nuts:hazelnuts': 'Lískové ořechy',
  'nuts:almonds': 'Mandle',
  'nuts:cashews': 'Kešu',
  'fish:freshwater-fish': 'Sladkovodní ryby',
  'fish:saltwater-fish': 'Mořské ryby',
  'fish:fish-oil': 'Rybí tuk',
  'shellfish:shrimp': 'Krevety',
  'shellfish:crab': 'Krab',
  'shellfish:mussels': 'Mušle',
  'citrus:oranges': 'Pomeranče',
  'citrus:lemons': 'Citrony',
  'citrus:grapefruit': 'Grapefruit',
  'citrus:mandarins': 'Mandarinky',
  'cocoa:dark-choc': 'Hořká čokoláda',
  'cocoa:milk-choc': 'Mléčná čokoláda',
  'cocoa:cocoa': 'Kakao',
  'tomatoes:fresh-tomatoes': 'Čerstvá rajčata',
  'tomatoes:tomato-sauce': 'Rajčatová omáčka',
  'tomatoes:ketchup': 'Kečup',
  'strawberries:fresh-strawberries': 'Čerstvé jahody',
  'strawberries:strawberry-jam': 'Jahodový džem',
  'sesame:sesame-seeds': 'Sezamová semínka',
  'sesame:tahini': 'Tahini',
  // ── ADR-0017 slice 6 — regional expansion ──
  'grains:oats': 'Oves',
  'grains:rye': 'Žito',
  'grains:barley': 'Ječmen',
  'grains:buckwheat': 'Pohanka',
  'grains:millet': 'Jáhly',
  'grains:rice': 'Rýže',
  'seeds:poppy-seed': 'Mák',
  'seeds:sunflower-seed': 'Slunečnicová semínka',
  'seeds:pumpkin-seed': 'Dýňová semínka',
  'seeds:flax-seed': 'Lněné semínko',
  'legumes:lentils': 'Čočka',
  'legumes:beans': 'Fazole',
  'legumes:peas': 'Hrách',
  'legumes:chickpea': 'Cizrna',
  'legumes:lupin': 'Vlčí bob',
  'fruit:apple': 'Jablko',
  'fruit:pear': 'Hruška',
  'fruit:cherry': 'Třešně a višně',
  'fruit:plum': 'Švestka',
  'fruit:apricot': 'Meruňka',
  'fruit:peach': 'Broskev',
  'fruit:grapes': 'Hrozny',
  'fruit:currants': 'Rybíz',
  'fruit:blueberries': 'Borůvky',
  'fruit:raspberries': 'Maliny',
  'fruit:gooseberry': 'Angrešt',
  'exotic-fruit:banana': 'Banán',
  'exotic-fruit:kiwi': 'Kiwi',
  'exotic-fruit:mango': 'Mango',
  'exotic-fruit:passion-fruit': 'Marakuja',
  'exotic-fruit:pineapple': 'Ananas',
  'exotic-fruit:avocado': 'Avokádo',
  'carrot-root-veg:carrot': 'Mrkev',
  'carrot-root-veg:parsley-root': 'Petržel kořenová',
  'carrot-root-veg:parsnip': 'Pastinák',
  'carrot-root-veg:beetroot': 'Červená řepa',
  'carrot-root-veg:radish': 'Ředkev',
  'carrot-root-veg:celery': 'Celer',
  'cabbage-brassica:sauerkraut': 'Kysané zelí',
  'cabbage-brassica:cooked-cabbage': 'Dušené zelí',
  'cabbage-brassica:broccoli-cauliflower': 'Brokolice a květák',
  'cabbage-brassica:kohlrabi': 'Kedlubna',
  'cabbage-brassica:kale': 'Kapusta',
  'onion-garlic:onion': 'Cibule',
  'onion-garlic:garlic': 'Česnek',
  'onion-garlic:leek': 'Pórek',
  'mushroom:wild-mushrooms': 'Lesní houby',
  'mushroom:cultivated-mushrooms': 'Žampiony',
  'other-vegetables:cucumber': 'Okurka',
  'other-vegetables:zucchini': 'Cuketa',
  'other-vegetables:pumpkin': 'Dýně',
  'other-vegetables:spinach': 'Špenát',
  'other-vegetables:lettuce': 'Salát',
  'other-vegetables:sweet-pepper': 'Paprika (sladká)',
  'meat:beef': 'Hovězí',
  'meat:veal': 'Telecí',
  'meat:chicken': 'Kuřecí',
  'meat:turkey': 'Krůtí',
  'meat:duck-goose': 'Kachna a husa',
  'meat:rabbit': 'Králík',
  'meat:game': 'Zvěřina',
  'meat:lamb': 'Jehněčí',
  'meat:offal': 'Vnitřnosti a játra',
  'mustard:mustard-condiment': 'Stolní hořčice',
  'mustard:mustard-seed': 'Hořčičné semínko',
  'sulphites-additives:sulphites': 'Siřičitany',
  'sulphites-additives:benzoates': 'Benzoany',
  'sulphites-additives:nitrites': 'Dusitany',
  'sulphites-additives:glutamate': 'Glutaman',
  'sulphites-additives:colourings': 'Barviva',
  'vinegar-fermented:vinegar': 'Ocet',
  'vinegar-fermented:pickled-veg': 'Nakládaná zelenina',
  'yeast:bakers-yeast': 'Pekařské droždí',
  'yeast:yeast-extract': 'Kvasnicový extrakt',
  'sweeteners:honey': 'Med',
  'sweeteners:sugar': 'Cukr',
  'sweeteners:artificial-sweeteners': 'Umělá sladidla',
  'sweeteners:syrup': 'Sirup',
  'spices-herbs:caraway': 'Kmín',
  'spices-herbs:cinnamon': 'Skořice',
  'spices-herbs:pepper': 'Pepř',
  'spices-herbs:bay-leaf': 'Bobkový list',
  'spices-herbs:marjoram': 'Majoránka',
  'spices-herbs:chilli-pepper': 'Chilli paprika',
  'spices-herbs:paprika-powder': 'Mletá paprika',
  'coffee-tea:coffee': 'Káva',
  'coffee-tea:black-tea': 'Černý čaj',
  'coffee-tea:herbal-tea': 'Bylinkový čaj',
} as const;
