import type { FamilyId, CatalogFoodId } from '$lib/data/allergen-catalog/allergen-catalog';

export type FamilyStrings = {
  name: string;
};

export const familyStrings = {
  grains:             { name: 'Obiloviny'               },
  vegetables:         { name: 'Zelenina'                },
  fruit:              { name: 'Ovoce'                   },
  meat:               { name: 'Maso'                    },
  'fish-seafood':     { name: 'Ryby a plody moře'       },
  dairy:              { name: 'Mléko'                   },
  eggs:               { name: 'Vejce'                   },
  legumes:            { name: 'Luštěniny'               },
  'nuts-seeds':       { name: 'Ořechy a semínka'        },
  'fats-oils':        { name: 'Oleje a tuky'            },
  sweet:              { name: 'Sladké'                  },
  'spices-condiments':{ name: 'Koření, omáčky a droždí' },
  drinks:             { name: 'Nápoje a čaje'           },
  custom:             { name: 'Vlastní'                 },
} as const satisfies Record<FamilyId, FamilyStrings>;

export type FoodStrings = {
  name: string;
};

export const foodStrings = {
  // Food twins (§3a)
  vejce:               { name: 'Celé vejce'             },
  bilek:               { name: 'Bílek'                  },
  zloutek:             { name: 'Žloutek'                },
  'kravske-mleko':     { name: 'Kravské mléko'          },
  jogurt:              { name: 'Jogurt'                 },
  'psenice':           { name: 'Pšenice'                },
  tofu:                { name: 'Tofu'                   },
  sezam:               { name: 'Sezamová semínka'       },
  jahody:              { name: 'Jahody'                 },
  rajce:               { name: 'Rajče'                  },
  kukurice:            { name: 'Kukuřice'               },
  pomeranc:            { name: 'Pomeranč'               },
  'horka-cokolada':    { name: 'Hořká čokoláda'         },
  'mlecna-cokolada':   { name: 'Mléčná čokoláda'        },
  losos:               { name: 'Losos'                  },
  krevetky:            { name: 'Krevety'                },
  // Divergent placements (§3b)
  'sojove-mleko':      { name: 'Sójové mléko'           },
  'ryzove-mleko':      { name: 'Rýžové mléko'           },
  'mandlove-mleko':    { name: 'Mandlové mléko'         },
  'ovesne-mleko':      { name: 'Ovesné mléko'           },
  'kokosove-mleko':    { name: 'Kokosové mléko'         },
  'ovci-mleko':        { name: 'Ovčí mléko'             },
  'kozi-mleko':        { name: 'Kozí mléko'             },
  // Composite (§3c)
  hummus:              { name: 'Hummus'                 },
  'oriskova-cokolada': { name: 'Oříšková čokoláda'      },
  // Loose everyday foods (§3d)
  // Dairy products (cow/sheep/goat split)
  tvaroh:              { name: 'Tvaroh'                 },
  syr:                 { name: 'Sýr'                    },
  maslo:               { name: 'Máslo'                  },
  smetana:             { name: 'Smetana'                },
  brynza:              { name: 'Brynza'                 },
  'kozi-syr':          { name: 'Kozí sýr'               },
  ghi:                 { name: 'Ghí'                    },
  'rostlinne-maslo':   { name: 'Rostlinné máslo'        },
  ryze:                { name: 'Rýže'                   },
  pohanka:             { name: 'Pohanka'                },
  oves:                { name: 'Oves'                   },
  jecmen:              { name: 'Ječmen'                 },
  zito:                { name: 'Žito'                   },
  'proso-jahly':       { name: 'Proso / jáhly'          },
  quinoa:              { name: 'Quinoa'                 },
  okurka:              { name: 'Okurka'                 },
  cuketa:              { name: 'Cuketa'                 },
  spenat:              { name: 'Špenát'                 },
  'listovy-salat':     { name: 'Listový salát'          },
  paprika:             { name: 'Paprika'                },
  brokolice:           { name: 'Brokolice'              },
  mrkev:               { name: 'Mrkev'                  },
  pastynak:            { name: 'Pastyňák'               },
  celer:               { name: 'Celer'                  },
  redkev:              { name: 'Ředkev'                 },
  brambory:            { name: 'Brambory'               },
  cesnek:              { name: 'Česnek'                 },
  cibule:              { name: 'Cibule'                 },
  kvetak:              { name: 'Květák'                 },
  zeli:                { name: 'Zelí'                   },
  dyne:                { name: 'Dýně'                   },
  repa:                { name: 'Řepa'                   },
  bataty:              { name: 'Batáty'                 },
  lilek:               { name: 'Lilek'                  },
  houby:               { name: 'Houby'                  },
  jablko:              { name: 'Jablko'                 },
  hruska:              { name: 'Hruška'                 },
  merunka:             { name: 'Meruňka'                },
  broskev:             { name: 'Broskev'                },
  hrozny:              { name: 'Hrozny'                 },
  svestka:             { name: 'Švestka'                },
  tresne:              { name: 'Třešně'                 },
  boruvky:             { name: 'Borůvky'                },
  maliny:              { name: 'Maliny'                 },
  rybiz:               { name: 'Rybíz'                  },
  banan:               { name: 'Banán'                  },
  kiwi:                { name: 'Kiwi'                   },
  mango:               { name: 'Mango'                  },
  ananas:              { name: 'Ananas'                 },
  avokado:             { name: 'Avokádo'                },
  citron:              { name: 'Citron'                 },
  mandarinka:          { name: 'Mandarinka'             },
  grapefruit:          { name: 'Grapefruit'             },
  meloun:              { name: 'Meloun'                 },
  brusinky:            { name: 'Brusinky'               },
  ostruziny:           { name: 'Ostružiny'              },
  angrest:             { name: 'Angrešt'                },
  kureci:              { name: 'Kuřecí'                 },
  hovezi:              { name: 'Hovězí'                 },
  teleci:              { name: 'Telecí'                 },
  veprove:             { name: 'Vepřové'         },
  kruti:               { name: 'Krůtí'                  },
  jehnneci:            { name: 'Jehněčí'                },
  kachna:              { name: 'Kachna'                 },
  kralik:              { name: 'Králík'                 },
  zverina:             { name: 'Zvěřina'                },
  sunka:               { name: 'Šunka a uzeniny'        },
  sadlo:               { name: 'Sádlo'                  },
  treska:              { name: 'Treska'                 },
  pstruh:              { name: 'Pstruh'                 },
  tunak:               { name: 'Tuňák'                  },
  sardinky:            { name: 'Sardinky'               },
  makrela:             { name: 'Makrela'                },
  sled:                { name: 'Sleď'                   },
  halibut:             { name: 'Halibut'                },
  tilapie:             { name: 'Tilapie'                },
  kapr:                { name: 'Kapr'                   },
  sumec:               { name: 'Sumec'                  },
  pangas:              { name: 'Pangas'                 },
  musle:               { name: 'Mušle'                  },
  krab:                { name: 'Krab'                   },
  cocka:               { name: 'Čočka'                  },
  fazole:              { name: 'Fazole'                 },
  hrac:                { name: 'Hrách'                  },
  cizrna:              { name: 'Cizrna'                 },
  tempeh:              { name: 'Tempeh'                 },
  edamame:             { name: 'Edamame'                },
  'vlassky-orech':     { name: 'Vlašský ořech'          },
  mandle:              { name: 'Mandle'                 },
  liskove:             { name: 'Lískové ořechy'         },
  kesu:                { name: 'Kešu'                   },
  para:                { name: 'Para ořechy'            },
  arasidy:             { name: 'Arašídy'                },
  pekanove:            { name: 'Pekanové ořechy'        },
  pistacie:            { name: 'Pistácie'               },
  makadamove:          { name: 'Makadamové ořechy'      },
  kokos:               { name: 'Kokos'                  },
  'dynova-seminka':    { name: 'Dýňová semínka'         },
  'lnene-semenko':     { name: 'Lněné semínko'          },
  'slunecnicova-seminka': { name: 'Slunečnicová semínka'},
  chia:                { name: 'Chia'                   },
  mak:                 { name: 'Mák'                    },
  'konopna-seminka':   { name: 'Konopná semínka'        },
  kakao:               { name: 'Kakao'                  },
  karob:               { name: 'Karob'                  },
  med:                 { name: 'Med'                    },
  'javorovy-sirup':    { name: 'Javorový sirup'         },
  'agavovy-sirup':     { name: 'Agávový sirup'          },
  'cekankovy-sirup':   { name: 'Čekankový sirup'        },
  cukr:                { name: 'Cukr'                   },
  xylitol:             { name: 'Xylitol (březový cukr)' },
  stevie:              { name: 'Stévie'                 },
  sul:                 { name: 'Sůl'                    },
  'koreni-bylinky':    { name: 'Koření a bylinky'       },
  kecup:               { name: 'Kečup'                  },
  horcice:             { name: 'Hořčice'                },
  ocet:                { name: 'Ocet'                   },
  'olivovy-olej':      { name: 'Olivový olej'           },
  'repkovy-olej':      { name: 'Řepkový olej'           },
  'slunecnicovy-olej': { name: 'Slunečnicový olej'      },
  'lneny-olej':        { name: 'Lněný olej'             },
  'kokosovy-olej':     { name: 'Kokosový olej'          },
  'bylinny-caj':       { name: 'Bylinkový čaj'          },
  kava:                { name: 'Káva'                   },
  'cerny-caj':         { name: 'Černý čaj'              },
  'obilna-kava':       { name: 'Obilná káva (Caro)'     },
  pivo:                { name: 'Pivo'                   },
  vino:                { name: 'Víno'                   },
  'tvrdy-alkohol':     { name: 'Tvrdý alkohol'          },
  dzus:                { name: 'Džus'                   },
} as const satisfies Record<CatalogFoodId, FoodStrings>;
